#deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: focusflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: focusflow
  template:
    metadata:
      labels:
        app: focusflow
    spec:
      containers:
      - name: focusflow
        image: mrforust/focusflow:latest
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: focusflow-data-pvc

---
# ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: focusflow-ingress
  annotations:
    # ГЛАВНАЯ СТРОКА: связываем с нашим Issuer
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # Заставляем Traefik делать редирект на HTTPS (если настроен entrypoint)
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - focusflow.chernuha.space
      secretName: focusflow-tls-secret # Сюда прилетит готовый сертификат
  rules:
    - host: focusflow.chernuha.space
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: focusflow
                port:
                  number: 3000
---
#pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: focusflow-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
#service
apiVersion: v1
kind: Service
metadata:
  name: focusflow
spec:
  selector:
    app: focusflow
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
