name: Building FocusFlow image
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/focusflow:latest .
      - name: Push Docker Image to Registry
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/focusflow:latest

  deploy:
    needs: build
    runs-on: deploy-server
    steps:
      - uses: actions/checkout@v3
      - name: Setup Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "Writing kubeconfig from secrets"
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > $HOME/.kube/config
          echo "Setting up permissions"
          chmod 600 $HOME/.kube/config

      - name: Update app
        run: |
          export KUBECONFIG=$HOME/.kube/config
          kubectl rollout restart deployment focusflow
