name: Building FocusFlow image
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build npm package
        run: |
          npm install
          npm run build
      - name: Build Docker Image
        run: |
          docker build -t focusflow:latest .
      - name: Push Docker Image to Registry
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker tag focusflow:latest ${{ secrets.DOCKER_USERNAME }}/focusflow:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/focusflow:latest
      # - name: Push Docker Image to GitHub Container Registry
      #   run: |
      #     echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      #     docker tag focusflow:latest ghcr.io/${{ github.repository_owner }}/focusflow:latest
      #     docker push ghcr.io/${{ github.repository_owner }}/focusflow:latest
