name: Building FocusFlow image
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # - name: Build npm package
      #   run: |
      #     npm install
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/focusflow:latest .
      - name: Push Docker Image to Registry
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/focusflow:latest
      # - name: Push Docker Image to GitHub Container Registry
      #   run: |
      #     echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      #     docker tag focusflow:latest ghcr.io/${{ github.repository_owner }}/focusflow:latest
      #     docker push ghcr.io/${{ github.repository_owner }}/focusflow:latest
  deploy:
      needs: build
      runs-on: deploy-server
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
          
        - name: Setup Kubeconfig
          run: |
            # Создаем папку в домашней директории пользователя, под которым бежит раннер
            mkdir -p $HOME/.kube
            # Записываем конфиг из секретов
            echo "${{ secrets.KUBECONFIG_CONTENT }}" > $HOME/.kube/config
            # Выставляем права, чтобы kubectl не ругался
            chmod 600 $HOME/.kube/config

        - name: Update app
          run: |
            # Явно указываем использовать именно этот файл
            export KUBECONFIG=$HOME/.kube/config
            # Выполняем команду
            kubectl rollout restart deployment focusflow